[project]
name = "uvdemo"
version = "0.1.0"
description = "Demo project for the UV for the alternative for other options e.g. pip,py etc"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.116.1",
    "uvicorn>=0.35.0",
]
